### ISSUE TITLE
Group [2pts] - Setup Kanban

### ISSUE THREAD

**Issue by eduardosancho** [fherrerao/Recipe-App-Capstone#13]
[Project Requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md).

Our [Kanban](https://github.com/fherrerao/Recipe-App-Capstone/projects/1)

Distribute the workload between @fherrerao & @eduardosancho.

Create an issue for every requirement and add it to the kanban.

**Comment by Meltrust** [comment]
Hi @eduardosancho,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

The link featured on this issue should point to your kanban board, not to the project requirements.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by eduardosancho** [comment]
Just added the link to our Kanban! Sorry for that.

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi team,  

Your project is complete!


![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
